### PR TITLE
Refactor/transit layer 8

### PR DESCRIPTION
**Pull request by jucheng925**
-Created new jsx file for poi markers, transitfunction, transitmap and import it the home file.
-Created a button to toggle between see transit system and landmarks
-Currently issue with landmarks not showing up after third toggle
-Change advancedmarkers/info window to using react/google-maps library to keep it consistent and so it can work on the map

### CODE REVIEW

**Comment by jucheng925** [comment]
need to work on toggle transit layer on and off. refactoring some more after team discussion

**Comment by jucheng925** [comment]
created a toggle button. tested and working

**Comment by jucheng925** [comment]
@CJMiller17  - I refactor your code so it can merge properly in development branch (we are not using app.jsx anymore, but home.jsx), also during discussion with team, create a toggle button where you can hide and show the transit routes (aka polylines). After looking at your code, I remove the transit layer - I dont think it was doing anything. Please review the PR and merge if okay

**Comment by CJMiller17** [comment]
Looks great Julie! Thanks for all the hard work you are doing!

**Pull request merged**
